package com.uzaktanbildirim.mobile

import android.view.View
import android.view.ViewGroup
import android.widget.TextView

object UiTextLocalizer {
    private val exactMap = linkedMapOf(
        "Uzaktan Kontrol" to "Remote Control",
        "Ana Panel" to "Home",
        "Kisayollar" to "Shortcuts",
        "Dosyalar" to "Files",
        "Sistem" to "System",
        "Bildirimler" to "Notifications",
        "Ayarlar" to "Settings",
        "Bildirim, dosya ve sistem kontrolu." to "Notifications, files, and system control.",
        "Kisayol paneli" to "Shortcut panel",
        "Sirala" to "Reorder",
        "EXE, kisayol, klasor, URL, CMD, PowerShell ve Calistir komutlari ekleyebilirsin. Uzun basarak duzenle veya sil." to "You can add EXE, shortcut, folder, URL, CMD, PowerShell, and Run commands. Long press to edit or delete.",
        "Kartlara dokununca secili PC uzerinde calisir. Linkler varsayilan tarayicida, protokol linkleri destekleyen uygulamada acilir." to "Tap a tile to run it on the selected PC. Links open in the default browser or in the app that handles that protocol.",
        "Henuz kısayol eklenmedi. Son karttaki arti ile yeni bir tane ekleyebilirsin." to "No shortcuts yet. Use the plus tile to add one.",
        "Ilk kurulum rehberini ac" to "Open the initial setup guide",
        "Worker URL" to "Worker URL",
        "Telefon adi" to "Phone name",
        "Ayarlarimi kaydet" to "Save my settings",
        "Worker dosya modu: Kontrol ediliyor." to "Worker file mode: Checking.",
        "Arka plan calisma izni" to "Background activity permission",
        "Arka plan izni durumu kontrol ediliyor." to "Checking background permission status.",
        "Izni iste" to "Request permission",
        "Durumu kontrol et" to "Check status",
        "Temiz kurulumda Worker URL ve secili PC APK'nin icine gomulmez. Baglanti bilgilerini sonradan sen girersin." to "In a clean setup, the Worker URL and selected PC are not embedded into the APK. You enter the connection details later.",
        "Eslestirme kodu" to "Pairing code",
        "PC ile eslestir" to "Pair with PC",
        "PC durumunu yenile" to "Refresh PC status",
        "Secili PC: -" to "Selected PC: -",
        "Bilinmiyor" to "Unknown",
        "Eslemeyi kaldir" to "Remove pairing",
        "Secili Worker: R2 destegi kontrol ediliyor." to "Selected Worker: checking R2 support.",
        "Coklu PC secimi" to "Multi-PC selection",
        "Durum burada gorunecek." to "Status will appear here.",
        "Hesaptaki PC'ler burada ozetlenecek." to "PCs in the account will be summarized here.",
        "Bildirim ayarlari" to "Notification settings",
        "Bildirim tercihleri burada gorunecek." to "Notification preferences will appear here.",
        "Ayarlari yukle" to "Load settings",
        "Ayarlari kaydet" to "Save settings",
        "PC acilinca bildir" to "Notify when the PC starts",
        "PC kapaninca bildir" to "Notify when the PC shuts down",
        "Ajan kapaninca bildir" to "Notify when the agent closes",
        "Uyku modunu bildir" to "Notify on sleep",
        "Uyandiginda bildir" to "Notify on wake",
        "Baglanti kesildiginde bildir" to "Notify on disconnect",
        "Basarisiz komutlari bildir" to "Notify on failed commands",
        "Bildirim listesi limiti" to "Notification list limit",
        "Ornek: 10" to "Example: 10",
        "Bildirim merkezinde ayni anda kac bildirim gosterilecegini belirler. 5 ile 50 arasi bir deger kullan." to "Sets how many notifications are shown in the notification center at once. Use a value between 5 and 50.",
        "Guvenlik ve oturum" to "Security and session",
        "Kilitle" to "Lock",
        "Zorla kapat" to "Force shutdown",
        "Zorla yeniden baslat" to "Force restart",
        "Oturumu kapat" to "Log off",
        "Medya ve ses" to "Media and sound",
        "Sonraki" to "Next",
        "Onceki" to "Previous",
        "Ses +" to "Volume +",
        "Ses -" to "Volume -",
        "Mute / Sessize al" to "Mute / Unmute",
        "Uygulama baslat" to "Launch app",
        "Chrome + Spotify + Discord ac" to "Open Chrome + Spotify + Discord",
        "Custom uygulama yolu veya alias" to "Custom app path or alias",
        "Custom uygulama argumanlari (opsiyonel)" to "Custom app arguments (optional)",
        "Secili custom uygulamayi calistir" to "Run selected custom app",
        "Calisan islemler" to "Running processes",
        "Acik uygulamalar" to "Open apps",
        "Tum islemler" to "All processes",
        "Secilen process adi buraya gelir" to "The selected process name appears here",
        "Secili process'i kapat" to "Close selected process",
        "Sistem bilgisi" to "System information",
        "Sistem bilgilerini yenile" to "Refresh system information",
        "Sistem bilgileri burada gorunecek." to "System information will appear here.",
        "Clipboard ve klavye" to "Clipboard and keyboard",
        "Clipboard metni" to "Clipboard text",
        "Clipboard gonder" to "Send clipboard",
        "Clipboard oku" to "Read clipboard",
        "Temizle" to "Clear",
        "Clipboard senkronizasyonunu ac" to "Enable clipboard sync",
        "Clipboard senkronizasyonu kapali." to "Clipboard sync is off.",
        "Klavye ile gonderilecek metin" to "Text to send via keyboard",
        "Metni yaz" to "Type text",
        "Mouse" to "Mouse",
        "Touchpad alanı istekleri throttle'lar; normal kişisel kullanımda limiti çok sert zorlamaz." to "The touchpad area throttles requests; in normal personal use it does not hit the limit aggressively.",
        "Drag modu kapali" to "Drag mode off",
        "Orta tik" to "Middle click",
        "Yukari" to "Up",
        "Asagi" to "Down",
        "Sola" to "Left",
        "Saga" to "Right",
        "Sol tik" to "Left click",
        "Sag tik" to "Right click",
        "Scroll +" to "Scroll +",
        "Scroll -" to "Scroll -",
        "Dosya gezgini" to "File explorer",
        "Uzak klasor yolu (bos birak = diskler)" to "Remote folder path (leave blank = drives)",
        "Diskleri listele" to "List drives",
        "Klasoru listele" to "List folder",
        "Ust klasor" to "Parent folder",
        "Telefondan dosya yukle" to "Upload file from phone",
        "Secili dosya: -" to "Selected file: -",
        "Coklu secim kapali." to "Multi-select is off.",
        "Yeni klasor adi" to "New folder name",
        "Mevcut klasorde yeni klasor olustur" to "Create a new folder in the current folder",
        "Secili oge icin yeni ad" to "New name for selected item",
        "Secili dosyayi calistir" to "Run selected file",
        "Secili dosyayi indir" to "Download selected file",
        "Secili dosyayi onizle" to "Preview selected file",
        "Secimi temizle" to "Clear selection",
        "Secili ogeyi yeniden adlandir" to "Rename selected item",
        "Secili ogeyi sil" to "Delete selected item",
        "Secilen ogeleri toplu sil" to "Delete selected items",
        "Aktarim bekleniyor." to "Waiting for transfer.",
        "Bir klasore dokununca acilir. Uzun basarak oge sec, dosyaya dokunarak calistirma/indirme akisini kullan." to "Tap a folder to open it. Long press to select an item, and tap a file to use the run/download flow.",
        "Kamera" to "Camera",
        "Secili PC'deki kamerayi sec, tek kare al veya canli izle." to "Choose a camera on the selected PC, capture a single frame, or start live viewing.",
        "Kamera secimi" to "Camera selection",
        "Kamera listesini yenile" to "Refresh camera list",
        "Kalite" to "Quality",
        "Canli mod" to "Live mode",
        "Ayna modu" to "Mirror mode",
        "Tek kare al" to "Capture single frame",
        "Canli kamera izle" to "Start live camera",
        "Kamerayi durdur" to "Stop camera",
        "Kamera onizleme" to "Camera preview",
        "Kamera kapali." to "Camera is off.",
        "Kamera icin once bir PC sec." to "Select a PC first for the camera.",
        "Orijinal" to "Original",
        "Klasor" to "Folder",
        "Calistir komutu" to "Run command",
        "Tus kombinasyonu" to "Key combination",
        "Mor" to "Purple",
        "Zumrut" to "Emerald",
        "Clipboard temizle" to "Clear clipboard",
        "Klavye metni gonder" to "Send keyboard text",
        "Klavye metni bos olamaz." to "Keyboard text cannot be empty.",
        "Kaldirilacak eslesme bulunamadi." to "No pairing was found to remove.",
        "Listelenecek islem bulunamadi." to "No process was found to list.",
        "Secilebilir oge bulunamadi." to "No selectable item was found.",
        "Yukleniyor..." to "Loading...",
        "Sec" to "Select",
        "Indir" to "Download",
        "Screenshot alinamadi." to "Screenshot could not be captured.",
        "Kamera listesi aliniyor..." to "Loading camera list...",
        "Bu PC'de kullanilabilir kamera bulunamadi." to "No available camera was found on this PC.",
        "Kamera listesi alinamadi." to "The camera list could not be retrieved.",
        "Kamera listesi icin once bir PC sec." to "Select a PC first to load the camera list.",
        "Tek kare icin once bir PC sec." to "Select a PC first for a snapshot.",
        "Canli kamera icin once bir PC sec." to "Select a PC first for live camera.",
        "Once listeden bir kamera sec." to "Select a camera from the list first.",
        "Kameradan tek kare aliniyor..." to "Capturing a single frame from the camera...",
        "Tek kare hazir" to "Single frame ready",
        "Kamera tek kare hatasi." to "Camera snapshot error.",
        "Kamera canli izleme hazir" to "Live camera preview ready",
        "Kamera canli izleme baslatilamadi." to "Live camera preview could not be started.",
        "Kamera canli izleme hatasi." to "Live camera preview error.",
        "Kamera karesi alinamadi." to "The camera frame could not be retrieved.",
        "Kamera baska bir uygulama tarafindan kullaniliyor olabilir." to "The camera may already be in use by another application.",
        "Kameraya erisim reddedildi. Windows gizlilik ayarlarini kontrol et." to "Camera access was denied. Check the Windows privacy settings.",
        "Secili kamera" to "Selected camera",
        "Canli oturum" to "Live session",
        "Kare kare ac" to "Frame by frame",
        "Ayna" to "Mirror",
        "Drag modu acik" to "Drag mode on",
        "Drag modu kapali" to "Drag mode off",
        "Calistir" to "Run",
        "Duzenle" to "Edit",
        "Modifier tuslari" to "Modifier keys",
        "Ana tus" to "Primary key",
        "Ana tus sec" to "Select primary key",
        "Opsiyonel argumanlar" to "Optional arguments",
        "Kart rengi" to "Tile color",
        "PC'den sec" to "Pick from PC",
        "Kokler" to "Roots",
        "Ust" to "Up",
        "Bu klasoru sec" to "Select this folder",
        "Konum: Kokler" to "Location: Roots",
        "Yol okunamadi." to "The path could not be read.",
        "oge bulundu." to "items found.",
        "Secili renk" to "Selected color",
        "Bu kombinasyon desteklenmez" to "This combination is not supported",
        "Secili kombinasyon" to "Selected combination",
        "Bir kombinasyon sec. Ornek: Left Ctrl + Right Alt + Q" to "Select a combination. Example: Left Ctrl + Right Alt + Q",
        "Custom uygulama" to "Custom app",
        "Clipboard gonder" to "Send clipboard",
        "Clipboard oku" to "Read clipboard",
        "Clipboard temizle" to "Clear clipboard",
        "Secili dosyayi calistir" to "Run selected file",
        "Kisayol surukleme baslatilamadi." to "Shortcut dragging could not be started.",
        "Kisayol listenin sonuna tasindi." to "The shortcut was moved to the end of the list.",
        "Kisayol kaydedildi ama ikon bilgisi alinamadi:" to "The shortcut was saved but the icon information could not be retrieved:",
        "Bu Worker icin legacy dosya aktarim moduna gecildi." to "Legacy file transfer mode was enabled for this Worker.",
        "Ekran goruntusu" to "Screen capture",
        "Dosya onizleme" to "File preview",
        "Secili dosyanin hizli onizlemesi burada gosterilir." to "A quick preview of the selected file appears here.",
        "Screenshot iste" to "Request screenshot",
        "Buyut / ac" to "Zoom / open",
        "Screenshot indir" to "Download screenshot",
        "Resim / screenshot secip yukle" to "Choose and upload image / screenshot",
        "Orijinal canli onizleme" to "Original live preview",
        "Canli onizlemeyi durdur" to "Stop live preview",
        "1080p canli onizleme baslat" to "Start 1080p live preview",
        "Canli ekran onizlemesi kapali." to "Live screen preview is off.",
        "Son sonuc" to "Latest result",
        "Son komut sonucu burada gorunecek." to "The latest command result will appear here.",
        "Log" to "Log",
        "Yaklasik limit bilgisi burada gorunecek." to "Estimated limit information will appear here.",
        "Son 5 bildirim" to "Last 5 notifications",
        "Son 5 bildirim burada gorunecek." to "The last 5 notifications will appear here.",
        "Merkezi yenile" to "Refresh center",
        "Tumunu okundu yap" to "Mark all as read",
        "Arka plan izni onerilir" to "Background permission recommended",
        "Ilk kullanim" to "First use",
        "Bu uygulamayi ilk defa mi kullaniyorsunuz?" to "Are you using this app for the first time?",
        "Evet ilk defa kullaniyorum" to "Yes, I am using it for the first time",
        "Ilk kurulum rehberi" to "Initial setup guide",
        "Secili PC'yi degistir" to "Change selected PC",
        "Eslesmeyi kaldir" to "Remove pairing",
        "Kaldir" to "Remove",
        "Kisayol ekle" to "Add shortcut",
        "Kisayolu duzenle" to "Edit shortcut",
        "Kisayol adi" to "Shortcut name",
        "Kaydet" to "Save",
        "Guncelle" to "Update",
        "Kisayolu sil" to "Delete shortcut",
        "Sil" to "Delete",
        "Kaldir" to "Remove",
        "Ikonu yenile" to "Refresh icon",
        "Secilenleri sil" to "Delete selected items",
        "Secili ogeyi sil" to "Delete selected item",
        "Oge sil" to "Delete item",
        "Toplu silme" to "Bulk delete",
        "PC'den uygulama veya kisayol sec" to "Pick an app or shortcut from the PC",
        "PC'den EXE / kisayol sec" to "Pick an EXE / shortcut from the PC",
        "PC'den klasor sec" to "Pick a folder from the PC",
        "PC Screenshot" to "PC screenshot",
        "Bildirim ayarlari yuklendi." to "Notification settings loaded.",
        "Bildirim ayarlari kaydedildi." to "Notification settings saved.",
        "Bildirim ayarlari guncellendi." to "Notification settings updated.",
        "Tum bildirimler okundu yapildi." to "All notifications were marked as read.",
        "Eslestirilmis PC bulunamadi." to "No paired PC found.",
        "Hesaba bagli PC bulunamadi." to "No PC is linked to this account.",
        "Hesaba bagli PC bulunmuyor." to "No PC is linked to this account.",
        "Secilecek PC bulunamadi. Once durum yenile." to "No PC is available to select. Refresh the status first.",
        "Secili PC'yi degistir" to "Change selected PC",
        "Token worker'a bildirildi." to "The token was reported to the Worker.",
        "Token guncellenemedi." to "The token could not be updated.",
        "Dosya kaydetme iptal edildi." to "File save was cancelled.",
        "Siralama modu kapatildi." to "Reorder mode turned off.",
        "Bu Worker icin legacy dosya aktarim moduna gecildi." to "Legacy file transfer mode was enabled for this Worker.",
        "Worker dosya modu: Worker URL bekleniyor." to "Worker file mode: waiting for Worker URL.",
        "Secili Worker: URL girilmedi." to "Selected Worker: no URL entered.",
        "Worker dosya modu: R2 aktif. Buyuk dosya aktarimi hazir." to "Worker file mode: R2 active. Large file transfer is ready.",
        "Secili Worker: R2 destekliyor." to "Selected Worker: supports R2.",
        "Secili Worker: R2 yok, legacy mod aktif." to "Selected Worker: no R2, legacy mode is active.",
        "Worker dosya modu: Kontrol ediliyor. Gerekirse otomatik fallback denenir." to "Worker file mode: checking. Automatic fallback will be tried if needed.",
        "Worker R2 destekliyor. Dosya aktarimi gelismis modda calisacak." to "The Worker supports R2. File transfer will use advanced mode.",
        "Worker R2 desteklemiyor. Dosya aktarimi legacy modda calisacak." to "The Worker does not support R2. File transfer will use legacy mode.",
        "Worker dosya modu belirlenemedi. Uygulama gerektiğinde otomatik fallback deneyecek." to "The Worker file mode could not be determined. The app will try automatic fallback when needed.",
        "Ilk kontrol bekleniyor." to "Initial check pending.",
        "Secili PC" to "Selected PC",
        "Arka plan izni zaten acik." to "Background permission is already enabled.",
        "Bu cihazda batarya optimizasyon ayari acilamadi." to "The battery optimization screen could not be opened on this device.",
        "Ayarı ac" to "Open settings",
        "Sonra" to "Later",
        "Cevrim ici" to "Online",
        "Uykuda" to "Sleeping",
        "Cevrim disi" to "Offline",
        "Hazirlaniyor" to "Preparing",
        "Clipboard bos." to "Clipboard is empty.",
        "Once custom uygulama yolu sec." to "Select a custom app path first.",
        "Once bir klasor ac." to "Open a folder first.",
        "Yukleme icin once bir klasor ac." to "Open a folder first before uploading.",
        "Resim yuklemek icin once bir klasor ac." to "Open a folder first before uploading an image.",
        "Once listeden bir dosya sec." to "Select a file from the list first.",
        "Once listeden bir process sec." to "Select a process from the list first.",
        "Onizleme icin tek bir dosya sec." to "Select exactly one file for preview.",
        "Canli onizleme icin once bir PC sec." to "Select a PC first for live preview.",
        "Clipboard sync icin once bir PC sec." to "Select a PC first for clipboard sync.",
        "Worker URL gir." to "Enter the Worker URL.",
        "Secili PC bulunamadi. Once durum yenile." to "No selected PC was found. Refresh the status first.",
        "Son bildirim yok." to "No recent notifications.",
        "Kisayol listede bulunamadi." to "The shortcut was not found in the list.",
        "Kisayol ikonu yenilenemedi." to "The shortcut icon could not be refreshed.",
        "Kisayol surukleme baslatilamadi." to "Shortcut dragging could not be started.",
        "Siralama modunda karti basili tutup tasiyabilirsin." to "In reorder mode, press and hold a tile to move it.",
        "Siralama modu acik. Bir karti basili tutup surukleyerek yerini degistir. Sona tasimak icin arti kartina birakabilirsin." to "Reorder mode is on. Press and hold a tile to move it. Drop it on the plus tile to move it to the end.",
        "Kisayol listenin sonuna tasindi." to "The shortcut was moved to the end of the list.",
        "Kisayol kaydedildi ama ikon bilgisi alinamadi" to "The shortcut was saved but the icon information could not be retrieved",
        "Once custom uygulama yolu sec." to "Select a custom app path first.",
        "Silmek icin once bir oge sec." to "Select an item first to delete it.",
        "Toplu silme icin once ogeleri sec." to "Select items first for bulk delete.",
        "Yeniden adlandirmak icin oge secip yeni ad gir." to "Select an item and enter a new name to rename it.",
        "Yukleme icin once bir klasor ac." to "Open a folder first before uploading.",
        "Resim yuklemek icin once bir klasor ac." to "Open a folder first before uploading an image.",
        "Once listeden bir dosya sec." to "Select a file from the list first.",
        "Once screenshot al." to "Capture a screenshot first.",
        "Dosya icerigi alinamadi." to "The file content could not be retrieved.",
        "Dosya indirilemedi." to "The file could not be downloaded.",
        "Dosya yuklenemedi." to "The file could not be uploaded.",
        "Dosya telefona kaydedildi." to "The file was saved to the phone.",
        "Dosya indir" to "Download file",
        "Dosya yukle" to "Upload file",
        "Dosya onizleme" to "File preview",
        "R2 alani hazirlaniyor" to "Preparing R2 area",
        "Legacy dosya modu ile hazirlaniyor" to "Preparing in legacy file mode",
        "Onizleme dosyasi hazirlaniyor" to "Preparing preview file",
        "PC dosyayi hazirliyor" to "The PC is preparing the file",
        "R2'ye yukleme basladi" to "Upload to R2 started",
        "PC hedef klasore yaziyor" to "The PC is writing to the target folder",
        "Legacy dosya modu ile gonderiliyor" to "Sending in legacy file mode",
        "Telefon dosyasi okunuyor" to "Reading the phone file",
        "Dosya onizlemesi hazir." to "File preview is ready.",
        "Legacy dosya onizlemesi hazir." to "Legacy file preview is ready.",
        "Bu Worker R2 desteklemedigi icin legacy modda tek dosya limiti 256 KB." to "Because this Worker does not support R2, the single-file limit in legacy mode is 256 KB.",
        "Bu Worker R2 desteklemedigi icin legacy modda onizleme 256 KB ile sinirli." to "Because this Worker does not support R2, preview is limited to 256 KB in legacy mode.",
        "Secilen dosya 25 MB sinirini asiyor." to "The selected file exceeds the 25 MB limit.",
        "Secilen dosya okunamadi." to "The selected file could not be read.",
        "Onizleme dosyasi bos dondu." to "The preview file returned empty.",
        "Kisayol" to "Shortcut",
        "PC clipboard'u telefona alindi." to "PC clipboard received on the phone.",
        "Kapat" to "Close",
        "Iptal" to "Cancel",
        "Evet" to "Yes",
        "Hayir" to "No",
        "Kaldirilacak eslesme bulunamadi." to "No pairing was found to remove.",
        "Once kamera goruntusu al." to "Capture a camera frame first.",
        "Kamera goruntusu acilamadi." to "The camera image could not be opened.",
        "Yaklasik limit bilgisi eslesme sonrasi gorunur. Not: request sayisi tahminidir; R2 icin sabit gunluk veri limiti yoktur." to "Estimated limit information appears after pairing. Note: the request count is approximate; there is no fixed daily data limit for R2.",
        "Siralama acik" to "Reordering on",
        "Yeniden adlandir" to "Rename",
        "Oge sil" to "Delete item",
        "Toplu silme" to "Bulk delete"
    )

    private val regexRules = listOf(
        Regex("""^Secili PC: (.+)$""") to { m: MatchResult -> "Selected PC: ${m.groupValues[1]}" },
        Regex("""^Yerel IP'ler: (.+)$""") to { m: MatchResult -> "Local IPs: ${m.groupValues[1]}" },
        Regex("""^Dis IP: (.+)$""") to { m: MatchResult -> "External IP: ${m.groupValues[1]}" },
        Regex("""^OS surumu: (.+)$""") to { m: MatchResult -> "OS version: ${m.groupValues[1]}" },
        Regex("""^PC secildi: (.+)$""") to { m: MatchResult -> "PC selected: ${m.groupValues[1]}" },
        Regex("""^Telefon eslesti: (.+)$""") to { m: MatchResult -> "Phone paired: ${m.groupValues[1]}" },
        Regex("""^Kisayol hazir: (.+)$""") to { m: MatchResult -> "Shortcut ready: ${m.groupValues[1]}" },
        Regex("""^Kisayol silindi: (.+)$""") to { m: MatchResult -> "Shortcut deleted: ${m.groupValues[1]}" },
        Regex("""^Kisayol sona tasindi: (.+)$""") to { m: MatchResult -> "Shortcut moved to end: ${m.groupValues[1]}" },
        Regex("""^Kisayol sirasi guncellendi: (.+)$""") to { m: MatchResult -> "Shortcut order updated: ${m.groupValues[1]}" },
        Regex("""^Process secildi: (.+)$""") to { m: MatchResult -> "Process selected: ${m.groupValues[1]}" },
        Regex("""^Screenshot alindi: (\d+) x (\d+)$""") to { m: MatchResult -> "Screenshot captured: ${m.groupValues[1]} x ${m.groupValues[2]}" },
        Regex("""^PC durumu guncellendi\.$""") to { _: MatchResult -> "PC status refreshed." },
        Regex("""^Makine: (.+)$""") to { m: MatchResult -> "Machine: ${m.groupValues[1]}" },
        Regex("""^Kullanici: (.+)$""") to { m: MatchResult -> "User: ${m.groupValues[1]}" },
        Regex("""^OS: (.+)$""") to { m: MatchResult -> "OS: ${m.groupValues[1]}" },
        Regex("""^Islemci cekirdegi: (.+)$""") to { m: MatchResult -> "CPU cores: ${m.groupValues[1]}" },
        Regex("""^RAM: (.+)$""") to { m: MatchResult -> "RAM: ${m.groupValues[1]}" },
        Regex("""^Surec sayisi: (.+)$""") to { m: MatchResult -> "Process count: ${m.groupValues[1]}" },
        Regex("""^Diskler:$""") to { _: MatchResult -> "Drives:" },
        Regex("""^(.+) icin clipboard senkronizasyonu hazir\. Telefonda kopyalanan yazi uygulama acikken gonderilir\.$""") to { m: MatchResult -> "Clipboard sync is ready for ${m.groupValues[1]}. Text copied on the phone is sent while the app is open." },
        Regex("""^(.+) icin clipboard senkronizasyonu kapali\.$""") to { m: MatchResult -> "Clipboard sync is off for ${m.groupValues[1]}." },
        Regex("""^(.+) icin canli ekran onizlemesi hazir \((.+)\)\.$""") to { m: MatchResult -> "Live screen preview is ready for ${m.groupValues[1]} (${m.groupValues[2]})." },
        Regex("""^(.+) icin canli ekran onizlemesi kapali\.$""") to { m: MatchResult -> "Live screen preview is off for ${m.groupValues[1]}." },
        Regex("""^Canli onizleme acik • (.+) • (\d+) x (\d+)$""") to { m: MatchResult -> "Live preview active • ${m.groupValues[1]} • ${m.groupValues[2]} x ${m.groupValues[3]}" },
        Regex("""^Kamera listesi hazir\. (\d+) kamera bulundu\.$""") to { m: MatchResult -> "Camera list ready. ${m.groupValues[1]} cameras found." },
        Regex("""^(.+) icin kamera hazir\. Bir kamera secip tek kare veya canli izleme baslat\.$""") to { m: MatchResult -> "Camera is ready for ${m.groupValues[1]}. Select a camera and start a snapshot or live preview." },
        Regex("""^(.+) icin kamera canli izleme hazir \((.+), (.+)\)\.$""") to { m: MatchResult -> "Live camera preview is ready for ${m.groupValues[1]} (${translate(m.groupValues[2])}, ${translate(m.groupValues[3])})." },
        Regex("""^Kamera canli izleme baslatiliyor \((.+), (.+)\)\.$""") to { m: MatchResult -> "Starting live camera preview (${translate(m.groupValues[1])}, ${translate(m.groupValues[2])})." },
        Regex("""^Kamera canli izleme acik • (.+) • (.+) • (.+)$""") to { m: MatchResult -> "Live camera preview active • ${m.groupValues[1]} • ${translate(m.groupValues[2])} • ${translate(m.groupValues[3])}" },
        Regex("""^(Tek kare hazir|Kamera canli izleme hazir) • (.+) • (\d+) x (\d+) • (.+?)( • Ayna)?$""") to { m: MatchResult ->
            val prefix = translate(m.groupValues[1])
            val mirror = if (m.groupValues[6].isNotBlank()) " • ${translate("Ayna")}" else ""
            "$prefix • ${m.groupValues[2]} • ${m.groupValues[3]} x ${m.groupValues[4]} • ${translate(m.groupValues[5])}$mirror"
        },
        Regex("""^Clipboard senkronizasyonu acik\. Uygulama acikken telefondan kopyaladigin yazi (.+) cihazina gonderilir\. Yeni PC kopyalamalari otomatik gelir\.$""") to { m: MatchResult -> "Clipboard sync is on. While the app is open, text copied on the phone is sent to ${m.groupValues[1]}. New PC clipboard updates arrive automatically." },
        Regex("""^Clipboard senkronizasyonu acik\. Uygulama acikken telefondan kopyaladigin yazi (\d+) etkin PC'ye gonderilir\. Yeni PC kopyalamalari otomatik gelir\.$""") to { m: MatchResult -> "Clipboard sync is on. While the app is open, text copied on the phone is sent to ${m.groupValues[1]} active PCs. New PC clipboard updates arrive automatically." },
        Regex("""^Yerel clipboard (.+) cihazina gonderildi\.$""") to { m: MatchResult -> "Local clipboard sent to ${m.groupValues[1]}." },
        Regex("""^Yerel clipboard (\d+) etkin PC'ye gonderildi\.$""") to { m: MatchResult -> "Local clipboard sent to ${m.groupValues[1]} active PCs." },
        Regex("""^Yerel ayarlar kaydedildi\.$""") to { _: MatchResult -> "Local settings saved." },
        Regex("""^FCM token alindi\.$""") to { _: MatchResult -> "FCM token received." },
        Regex("""^FCM token alinamadi: (.+)$""") to { m: MatchResult -> "Could not receive FCM token: ${m.groupValues[1]}" },
        Regex("""^Bu Worker icin legacy dosya aktarim moduna gecildi\.$""") to { _: MatchResult -> "Legacy file transfer mode was enabled for this Worker." },
        Regex("""^Worker URL degisti\. Eski eslesme ve oturum bilgileri temizlendi\.$""") to { _: MatchResult -> "Worker URL changed. Old pairing and session data were cleared." },
        Regex("""^Worker hatasi \(1101\): (.+)$""") to { m: MatchResult -> "Worker error (1101): ${m.groupValues[1]}" },
        Regex("""^Bir sonraki otomatik kontrol: (.+)$""") to { m: MatchResult -> "Next automatic check: ${m.groupValues[1]}" },
        Regex("""^Son (\d+) bildirim$""") to { m: MatchResult -> "Last ${m.groupValues[1]} notifications" },
        Regex("""^Son (\d+) bildirim burada gorunecek\.$""") to { m: MatchResult -> "The last ${m.groupValues[1]} notifications will appear here." },
        Regex("""^Son (\d+) bildirim • okunmamis: (\d+)$""") to { m: MatchResult -> "Last ${m.groupValues[1]} notifications • unread: ${m.groupValues[2]}" },
        Regex("""^Arka plan calisma izni acik\. Bildirimler, canli baglanti ve PC'den telefona gelen pano daha stabil calisir\.$""") to { _: MatchResult -> "Background activity permission is enabled. Notifications, the live connection, and clipboard updates from the PC will work more reliably." },
        Regex("""^Arka plan calisma izni kapali gorunuyor\. Batarya optimizasyonu bildirimleri, canli baglantiyi ve PC'den telefona gelen panoyu zayiflatabilir\.$""") to { _: MatchResult -> "Background activity permission appears to be off. Battery optimization may weaken notifications, the live connection, and clipboard updates from the PC." },
        Regex("""^Not: Android 10\+ kisiti nedeniyle telefondan PC'ye pano senkronu sadece uygulama acikken calisir\.$""") to { _: MatchResult -> "Note: because of the Android 10+ restriction, phone-to-PC clipboard sync works only while the app is open." },
        Regex("""^Bu cihazda ayrica Otomatik baslat ve pil kisitini Sinirsiz/Yok olarak ayarlamak gerekebilir\.$""") to { _: MatchResult -> "On this device you may also need to enable Auto Start and set battery restrictions to Unlimited/None." },
        Regex("""^Xiaomi/Redmi/POCO cihazlarda ayrica Otomatik baslat ve pil kisitini Sinirsiz/Yok yap\.$""") to { _: MatchResult -> "On Xiaomi/Redmi/POCO devices you may also need to enable Auto Start and set battery restrictions to Unlimited/None." },
        Regex("""^(.+) -> (.+)$""") to { m: MatchResult -> "${m.groupValues[1]} -> ${translate(m.groupValues[2])}" },
        Regex("""^(.+) \| son olay: (.+)$""") to { m: MatchResult -> "${m.groupValues[1]} | latest event: ${m.groupValues[2]}" },
        Regex("""^Son gorulme: (.+)$""") to { m: MatchResult -> "Last seen: ${m.groupValues[1]}" },
        Regex("""^Canli ekran onizlemesi baslatildi \((.+)\)\.$""") to { m: MatchResult -> "Live screen preview started (${m.groupValues[1]})." },
        Regex("""^Okunmamis bildirim sayisi: (\d+)$""") to { m: MatchResult -> "Unread notification count: ${m.groupValues[1]}" },
        Regex("""^(.+) eslesmesi telefondan kaldirildi\.$""") to { m: MatchResult -> "${m.groupValues[1]} pairing was removed from the phone." },
        Regex("""^(.+) kaldirildi\. Kalan cihazlar yenileniyor\.$""") to { m: MatchResult -> "${m.groupValues[1]} was removed. Refreshing remaining devices." },
        Regex("""^Tum islemler \((\d+)\)$""") to { m: MatchResult -> "All processes (${m.groupValues[1]})" },
        Regex("""^Acik / gorunen uygulamalar \((\d+)\)$""") to { m: MatchResult -> "Open / visible apps (${m.groupValues[1]})" },
        Regex("""^Listelenen process sayisi: (\d+)$""") to { m: MatchResult -> "Listed process count: ${m.groupValues[1]}" },
        Regex("""^Dosya yuklendi: (.+)$""") to { m: MatchResult -> "File uploaded: ${m.groupValues[1]}" },
        Regex("""^Telefon dosyasi yuklendi: (.+)$""") to { m: MatchResult -> "Phone file uploaded: ${m.groupValues[1]}" },
        Regex("""^Telefon dosyasi legacy modda yuklendi: (.+)$""") to { m: MatchResult -> "Phone file uploaded in legacy mode: ${m.groupValues[1]}" },
        Regex("""^Dosya telefona kaydedildi: (.+)$""") to { m: MatchResult -> "The file was saved to the phone: ${m.groupValues[1]}" },
        Regex("""^(.+) kaldirilsin mi\?$""") to { m: MatchResult -> "Remove ${m.groupValues[1]}?" },
        Regex("""^(.+) kaldirildi\.$""") to { m: MatchResult -> "${m.groupValues[1]} was removed." },
        Regex("""^(\d+) oge silinsin mi\?$""") to { m: MatchResult -> "Delete ${m.groupValues[1]} items?" },
        Regex("""^(\d+) oge bulundu\.$""") to { m: MatchResult -> "${m.groupValues[1]} items found." },
        Regex("""^(.+) kalici olarak silinsin mi\?$""") to { m: MatchResult -> "Permanently delete ${m.groupValues[1]}?" },
        Regex("""^Konum: (.+)$""") to { m: MatchResult -> "Location: ${m.groupValues[1]}" },
        Regex("""^(.+) telefona aliniyor$""") to { m: MatchResult -> "${m.groupValues[1]} is being transferred to the phone" },
        Regex("""^Canli ekran onizlemesi icin once bir PC sec\.$""") to { _: MatchResult -> "Select a PC first for live screen preview." },
        Regex("""^Clipboard sync icin once bir PC sec\.$""") to { _: MatchResult -> "Select a PC first for clipboard sync." },
        Regex("""^Once PC ile esles\.$""") to { _: MatchResult -> "Pair with a PC first." },
        Regex("""^Kisayollar icin once Worker ayarini girip bir PC sec\.$""") to { _: MatchResult -> "Enter the Worker settings and select a PC first for shortcuts." },
        Regex("""^Hotkey icin bir ana tus sec\.$""") to { _: MatchResult -> "Select a primary key for the hotkey." },
        Regex("""^Ctrl \+ Alt \+ Delete desteklenmiyor\.$""") to { _: MatchResult -> "Ctrl + Alt + Delete is not supported." },
        Regex("""^Kisayol hedefi bos olamaz\.$""") to { _: MatchResult -> "Shortcut target cannot be empty." },
        Regex("""^Kopyalanacak esleme kodu yok\.$""") to { _: MatchResult -> "There is no pairing code to copy." },
        Regex("""^Esleme kodu panoya kopyalandi\.$""") to { _: MatchResult -> "Pairing code copied to the clipboard." },
        Regex("""^Bagli$""") to { _: MatchResult -> "Connected" },
        Regex("""^Bagli degil$""") to { _: MatchResult -> "Not connected" },
        Regex("""^Eslendi$""") to { _: MatchResult -> "Paired" },
        Regex("""^Esleme bekliyor$""") to { _: MatchResult -> "Waiting for pairing" },
        Regex("""^YENI ?$""") to { _: MatchResult -> "NEW " }
    )

    fun translate(text: CharSequence?): String {
        val raw = text?.toString().orEmpty()
        if (!BuildConfig.FORCE_ENGLISH || raw.isBlank()) {
            return raw
        }
        return raw.split("\n").joinToString("\n") { translateLine(it) }
    }

    private fun translateLine(line: String): String {
        if (line.isBlank()) {
            return line
        }
        val bulletPrefix = if (line.startsWith("• ")) "• " else ""
        val content = if (bulletPrefix.isNotEmpty()) line.removePrefix(bulletPrefix) else line
        exactMap[content]?.let { return bulletPrefix + it }
        for ((regex, replacement) in regexRules) {
            val match = regex.matchEntire(content) ?: continue
            return bulletPrefix + replacement(match)
        }
        return bulletPrefix + content
    }

    fun applyToViewTree(root: View?) {
        if (!BuildConfig.FORCE_ENGLISH || root == null) {
            return
        }
        val translatedContentDescription = translate(root.contentDescription)
        if (translatedContentDescription.isNotBlank() && translatedContentDescription != root.contentDescription?.toString()) {
            root.contentDescription = translatedContentDescription
        }
        when (root) {
            is TextView -> {
                val translatedText = translate(root.text)
                if (translatedText.isNotBlank() && translatedText != root.text?.toString()) {
                    root.text = translatedText
                }
                val translatedHint = translate(root.hint)
                if (translatedHint.isNotBlank() && translatedHint != root.hint?.toString()) {
                    root.hint = translatedHint
                }
            }
        }
        if (root is ViewGroup) {
            for (index in 0 until root.childCount) {
                applyToViewTree(root.getChildAt(index))
            }
        }
    }
}
